### ISSUE TITLE
--barcode-file option from snaptools snap-pre doesnt seem to work

### ISSUE THREAD

**Issue by opoirion** [r3fang/SnapATAC#84] opened 2019-09-04 22:43 UTC
Hi Rongxin.

the --barcode-file option from the snaptools seem to have no effect:

snaptools snap-pre --input-file tmp.repl1_TEST5.sorted.bed.gz --genome-size mm10.genome.size --output-snap repl1_TEST5.snap --barcode-file tmp.repl1_TEST5.xgi --overwrite True --genome-name mm10 --keep-chrm False

and 

snaptools snap-pre --input-file tmp.repl1_TEST5.sorted.bed.gz --genome-size mm10.genome.size --output-snap repl1_TEST5.snap  --overwrite True --genome-name mm10 --keep-chrm False

give both a snap file with the same number of barcodes (equal to the total number of barcodes in the dataset)

**Comment by r3fang** [comment] 2019-09-04 23:32
Hi Olivier,

Indeed, it is a problem that I have fixed for a while. This problem is caused by the conflict between `—min-cov` and `—barcode-file`. But it should be fixed now. If you can update to the latest version 1.4.8, the problem should be gone.

Best,
--
Rongxin Fang, Ren Lab
Ludwig Cancer Research
Bioinformatics Ph.D. Student
University of California, San Diego

**Closed** 2019-09-06 16:44 UTC
