### ISSUE TITLE
Error when running JDA dimensionality step

### ISSUE THREAD

**Issue by danielgchen** [r3fang/SnapATAC#77] opened 2019-08-28 17:18 UTC
Hi, I was following your tutorial and everything seems to work great until the JDA dimension reduction step which came up with some errors shown below,
I first tried the normalization method listed in the tutorial but since that wasn't an available method I switched to 'residual' because it was listed as one of the available normalization steps but that came up with the issue of JDA not having a method parameter, in another screen shot below? Do you know how I should change my code to run it? This is not 10x data, btw if that helps, thanks!
![image](https://user-images.githubusercontent.com/51771449/63877645-de0c8180-c97c-11e9-9f85-299ec8b3746d.png)
![image](https://user-images.githubusercontent.com/51771449/63877846-3ba0ce00-c97d-11e9-9a97-781ae8e1da68.png)

**Comment by r3fang** [comment] 2019-08-28 18:27
Hi I am sorry for the trouble. The issue is because I started updating the package yesterday and it is still ongoing. Can you follow this tutorial:

https://github.com/r3fang/SnapATAC/blob/master/examples/10X_PBMC_15K/README.md <https://github.com/r3fang/SnapATAC/blob/master/examples/10X_PBMC_15K/README.md>

Let me know if it does not work 

--
Rongxin Fang
Ph.D. Student, Ren Lab
Ludwig Institute for Cancer Research
University of California, San Diego

**Comment by r3fang** [comment] 2019-08-28 18:59
the barcode.csv file is just for barcode selection, you don’t need this for cell selection. Instead, you just can filter the cells based on the number of fragments etc. 

--
Rongxin Fang
Ph.D. Student, Ren Lab
Ludwig Institute for Cancer Research
University of California, San Diego

**Comment by r3fang** [comment] 2019-08-28 19:55
that’s because you are still filtering the barcode using the single cell tsv file which is embedded in the snap object as metaData

--
Rongxin Fang
Ph.D. Student, Ren Lab
Ludwig Institute for Cancer Research
University of California, San Diego

**Comment by r3fang** [comment] 2019-08-28 22:55
i think this step is wrong:

row.covs.dens <- density(
  x = x.sp@metaData[,"logUMI"], 
  bw = 'nrd', adjust = 1
)

1) you are sampling based on the coverage but your  x.sp@metaData object does not have a column called logUMI. Instead you can used log10(x.sp@metaData[“UQ"] +1); Does it work?

2) or you don’t need to sample landmarks if you have small number of cells. After filtering the low-quality cells, you just skip step 3-4 and treat x.sp as x.landmark.sp.

Let me know if you have more questions about it! Also, i will add another example where no landmark sampling is performed. 

--
Rongxin Fang
Ph.D. Student, Ren Lab
Ludwig Institute for Cancer Research
University of California, San Diego

**Comment by danielgchen** [comment] 2019-08-30 15:59
Thanks, I'll try that

**Comment by danielgchen** [comment] 2019-08-30 17:34
Alright so when I change that to the code you gave it produces an error, if you could find another solution that would be great, but since I don't have much cells it's fine too.
![image](https://user-images.githubusercontent.com/51771449/64040399-c9adbd80-cb11-11e9-81af-0933f7f6954a.png)

**Comment by danielgchen** [comment] 2019-08-30 17:41
Also when I run the diffusion map step I run into this error, this is after I set x.landmark.sp to x.sp
![image](https://user-images.githubusercontent.com/51771449/64040691-6c663c00-cb12-11e9-8dcf-5587d3185d6b.png)
more screenshots for reference
![image](https://user-images.githubusercontent.com/51771449/64040806-b2bb9b00-cb12-11e9-97c4-c96dd2941a94.png)

**Comment by danielgchen** [comment] 2019-08-30 19:39
Also, when I plot the tsne graph and specify point.color to be cluster I don't get the clusters, as shown below the clusters parameter is filled, but nothing is shown in the graph
![image](https://user-images.githubusercontent.com/51771449/64047288-37aeb080-cb23-11e9-99bd-8d7f58d35fa1.png)

**Comment by r3fang** [comment] 2019-09-05 16:32
Hi there,

1) 
the sampling issue should be fixed, please check the first and second example in the GitHub. 
https://github.com/r3fang/SnapATAC/blob/master/examples/10X_brain_5k/README.md <https://github.com/r3fang/SnapATAC/blob/master/examples/10X_brain_5k/README.md>
https://github.com/r3fang/SnapATAC/blob/master/examples/10X_PBMC_15K/README.md <https://github.com/r3fang/SnapATAC/blob/master/examples/10X_PBMC_15K/README.md>

2) can you please check if `x.sp@cluster` has the cluster label?

Sorry that you just installed the package when I was updating it.

Best,
--
Rongxin Fang
Ph.D. Student, Ren Lab
Ludwig Institute for Cancer Research
University of California, San Diego

**Comment by danielgchen** [comment] 2019-09-07 23:45
Hi,

No worries, so I followed the new 10x PBMC 15k tutorial and updated the package but I am still running into the same sampling issue for the DiffusionMap step as shown below:
![image](https://user-images.githubusercontent.com/51771449/64481321-d88a1500-d18e-11e9-82dc-2346dff2c849.png)
and in my session info it does say I updated SnapATAC
![image](https://user-images.githubusercontent.com/51771449/64481323-dfb12300-d18e-11e9-9113-edbedaa178ad.png)

**Comment by r3fang** [comment] 2019-09-07 23:46
Thanks! Can you reinstall the package and try it again?

--
Rongxin Fang, Ren Lab
Ludwig Cancer Research
Bioinformatics Ph.D. Student
University of California, San Diego

**Comment by danielgchen** [comment] 2019-09-07 23:49
Also for the x.lda.sp@cluster this is what shows up:
![image](https://user-images.githubusercontent.com/51771449/64481329-1ab35680-d18f-11e9-93ca-1d81f5736351.png)
and when I look at the object here:
![image](https://user-images.githubusercontent.com/51771449/64481358-6960f080-d18f-11e9-9fd9-05ea5dedff04.png)
there seems to be a cluster label:
![image](https://user-images.githubusercontent.com/51771449/64481350-58b07a80-d18f-11e9-8b6c-349abff05e6f.png)

**Comment by r3fang** [comment] 2019-09-07 23:51
Again, the version you have downloaded was right in the middle of updates, if you can reinstall the package, I expect all these errors would be gone

**Comment by danielgchen** [comment] 2019-09-09 17:52
Hi,

I tried to reinstall the package and got this:
![image](https://user-images.githubusercontent.com/51771449/64554242-dbe8e200-d2ef-11e9-8b7b-7dc5193463d2.png)
then I set the force parameter to true, but none of the previous issues were resolved

**Comment by r3fang** [comment] 2019-09-09 17:55
can you repeat the first example?
https://github.com/r3fang/SnapATAC/blob/master/examples/10X_brain_5k/README.md <https://github.com/r3fang/SnapATAC/blob/master/examples/10X_brain_5k/README.md>

**Comment by danielgchen** [comment] 2019-09-13 18:24
Hi,
I just redownloaded the newest SnapATAC, from 13 hours ago, and diffusion map is working now and the clusters, thank you!

**Comment by danielgchen** [comment] 2019-09-13 22:47
Hi, 

When I try to run chromVAR it says the method is unavailable even though on Git it says it is
![image](https://user-images.githubusercontent.com/51771449/64898892-c9e3a800-d63d-11e9-9865-56fc5756e0d5.png)

**Comment by danielgchen** [comment] 2019-09-21 00:54
Hi,

I just downloaded your most recent update and now can run chromVAR, thank you! However, I am unable to recreate the plots that you had, when I try I get:
![image](https://user-images.githubusercontent.com/51771449/65365531-f9ab2680-dbce-11e9-8ebb-582fe29b8447.png)
using the code:
```
motif_i = "MA0909.1_HOXD13";
dat = data.frame(x=x.lda.sp@metaData[,"cluster"], y=x.lda.sp@mmat[,motif_i])
p1 <- ggplot(dat, aes(x=x, y=y, fill=x)) + 
  theme_classic() +
  geom_violin() + 
  xlab("cluster") +
  ylab("motif enrichment") + 
  ggtitle(motif_i) +
  theme(
    plot.margin = margin(5,1,5,1, "cm"),
    axis.text.x = element_text(angle = 90, hjust = 1),
    axis.ticks.x=element_blank(),
    legend.position = "none"
  )
p1
```
here is some information about the snap object:
![image](https://user-images.githubusercontent.com/51771449/65365555-32e39680-dbcf-11e9-8d53-6070c4d6010a.png)
and the dat object looks like:
![image](https://user-images.githubusercontent.com/51771449/65365563-3f67ef00-dbcf-11e9-86a0-f5d4962071bd.png)
any suggestions? thanks!
aiming for plots like this, as shown in your guide:
![image](https://user-images.githubusercontent.com/51771449/65365609-abe2ee00-dbcf-11e9-9a5c-b126aeef5f99.png)

**Comment by r3fang** [comment] 2019-10-02 13:21
hi sorry for the late response!

this is a bit wired. Have you figured out this issue? can you remove theme and try it again

> p1 <- ggplot(dat, aes(x=x, y=y, fill=x)) + 
>   theme_classic() +
>   geom_violin() + 
>   xlab("cluster") +
>   ylab("motif enrichment") + 
>   ggtitle(motif_i) 

`

and let me know the outcome?
--
Rongxin Fang
Ph.D. Student, Ren Lab
Ludwig Institute for Cancer Research
University of California, San Diego

**Closed** 2020-02-06 08:59 UTC
